name: Add Tag

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to add'
        required: true
        type: string
      is-latest:
        description: 'Handle add or update latest tag'
        required: false
        default: true
        type: boolean

jobs:
  check-tag-exists:
    name: Check if tag exists
    uses: ./.github/workflows/check-tag-exists.yml
    with:
      tag: ${{ inputs.tag }}

  create-tag:
    needs: check-tag-exists
    if: ${{ !needs.check-tag-exists.outputs.exists == 'true'}}
    name: Create and push Tag
    uses: ./.github/workflows/create-push-tags.yml
    with:
      tag: ${{ needs.check-tag-exists.outputs.tag }}
      is-latest: ${{ inputs.is-latest }}