name: Add Tag

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to add'
        required: true
        type: string
      is-latest:
        description: 'Handle add or update latest tag'
        required: false
        default: true
        type: boolean

jobs:
  create-tag:
    name: Create and push Tag
    uses: ./.github/workflows/create-push-tags.yml
    with:
      tag: ${{ inputs.tag }}
      is-latest: ${{ inputs.is-latest == 'true' }}