name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be added'
        required: true
        type: string
      is-latest:
        description: 'Is latest version'
        required: false
        default: true
        type: boolean

jobs:
  add-tag:
    name: Release workflow
    uses: ./.github/workflows/add-tag.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      is-latest: ${{ github.event.inputs.is-latest  == 'true'}}
