name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be added'
        required: true
        type: string
      is-latest:
        description: 'Is latest version'
        required: false
        default: true
        type: boolean

jobs:
  check-tag-exists:
    name: Check if tag exists
    uses: .github/workflows/check-tag-exists.yml
    with:
      tag: ${{ inputs.tag }}
      remote-name: ${{ inputs.remote-name }}

  create-tag:
    needs: check-tag-exists
    if: ${{ needs.check-tag-exists.outputs.exists == 'false'}}
    name: Create and push Tag
    uses: .github/workflows/create-push-tags.yml
    with:
      tag: ${{ needs.check-tag-exists.outputs.tag }}
      remote-name: ${{ inputs.remote-name }}
      is-latest: ${{ inputs.is-latest }}
