name: Self Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be added'
        required: true
        type: string
      is-latest:
        description: 'Handle add or update latest tag'
        required: false
        default: true
        type: boolean

jobs:
  self-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add tag
        uses: JanCodeLab/workflows/add-tag.yml@main
        with:
          tag: ${{ github.event.inputs.tag }}
          is-latest: ${{ github.event.inputs.is-latest }}